### ISSUE TITLE
[BUG] \cdot gets overwritten

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#126]
Currently, typing `cdot` gets replaced by `\dot{c}`, and typing `\cdot` gets replaced by `\\dot{c}`, leaving no way to obtain `\cdot` (without editing the inserted snippets). I think this was a recent change since `cdot` used to work?

**Comment by cbschen** [comment]
Resonating on this, I think a more general issue is the priority setting of the trigger. 

For example, if I type $\beta$, it will be autocorrected with $\b\eta$, due to the high priority of trigger $eta$. 

Similar issues happens in a lot of places and it does not seem to be able to recognize the backslash $\$ that I have manually typed. 

A proposed solution as a feature request is to lower the priority of the trigger such that when it detects backslash $\$ and manual command following backslash, it does not autocorrect the expression. 

Follow up on this would be greatly appreciated.

**Comment by cbschen** [comment]
> Currently, typing `cdot` gets replaced by `\dot{c}`, and typing `\cdot` gets replaced by `\\dot{c}`, leaving no way to obtain `\cdot` (without editing the inserted snippets). I think this was a recent change since `cdot` used to work?

Ok, I checked the document again and I guess it could be solved by modifying the default snippet and reduce the priority level or turn off the "auto" mode, depending on your personal preference.

**Comment by userrand** [comment]
> > Currently, typing `cdot` gets replaced by `\dot{c}`, and typing `\cdot` gets replaced by `\\dot{c}`, leaving no way to obtain `\cdot` (without editing the inserted snippets). I think this was a recent change since `cdot` used to work?
> 
> Ok, I checked the document again and I guess it could be solved by modifying the default snippet and reduce the priority level or turn off the "auto" mode, depending on your personal preference.

that would require doing it for each snippet. By far the most difficult part when using this plugin is that there is no rule that prevents autocompletion when the user types \ . Naively this seems possible.

**Comment by artisticat1** [comment]
This is resolved in the latest release, where `{trigger: "cdot", replacement: "\\cdot", options: "mA", priority: 2},` has been added to the default snippets.
