### ISSUE TITLE
Include Norm in Bracket behaviour

### ISSUE THREAD

**Issue by mscott99** [artisticat1/obsidian-latex-suite#42]
the idea would be to add “\|” and “\{“ “\}” as a bracket type, so that the auto-enlarge behaviour applies to norms.

Your plugin is great.

**Comment by artisticat1** [comment]
Good idea, I'll try to add this in one of the next releases.

**Comment by artisticat1** [comment]
This will be easy to do for `\{` and `\}`, because the open and close symbols are different.

However, "norm"  uses the same symbol `|` to denote the start and end. So I don't think it's possible, exactly, to determine which open symbol `|` should be paired with which close symbol `|` in the case of nested norms (e.g. $|a+b|c|d|$).

**Comment by mscott99** [comment]
Ooh that is very subtle. I see, it doesn’t seem possible.

**Comment by artisticat1** [comment]
1.4.2 adds `\{` and `\}` to the auto-enlarge brackets feature.

**Comment by mscott99** [comment]
Amazing thanks!

**Comment by mscott99** [comment]
Hello, I think this can be done via the \lVert \rVert commands for the norm instead of \| \|. I just learned about these.

**Comment by artisticat1** [comment]
> Hello, I think this can be done via the \lVert \rVert commands for the norm instead of | |. I just learned about these.

Thanks for the info! Added in 1.6.5.

**Comment by mscott99** [comment]
Amazing, thanks a lot!
