### ISSUE TITLE
Snippets don't work in Vim Mode

### ISSUE THREAD

**Issue by phibr0** [artisticat1/obsidian-latex-suite#53]
When Vim Mode is enabled, no sinppets are triggered when I type e.g. `mk`. No Errors in the console either.

**Comment by artisticat1** [comment]
After first enabling vim mode, snippets will work after you close & reopen the file you're editing. (Or after you reload Obsidian.) After this, the plugin should continue to work as usual for any new files you open.

Does this work for you?

(It's currently like this because I wasn't able to find a way to add an event listener that fires when the user changes the vim mode setting.)
