### ISSUE TITLE
Disable expanding short Greek letters

### ISSUE THREAD

**Issue by XintakXVI** [artisticat1/obsidian-latex-suite#55]
First time doing something on GitHub so pardon my inexperience.

As the [README](https://github.com/artisticat1/obsidian-latex-suite#:~:text=For%20greek%20letters%20with%20short%20names%20(2%2D3%20characters)%2C%20just%20type%20their%20name!%20e.g.%20%22pi%22%20%E2%86%92%20%22%5Cpi%22) says, typing Greek letters with short names will automatically prepend the `\` . e.g., Typing `xi` produces `\xi`.
However, this prevents a snippet triggered by `xii` from running.

Is there any way to disable this functionality so that the `xii` snippet will be triggered?

Great plugin! Thanks!

**Comment by artisticat1** [comment]
Yep! Here are some options:

- Comment out or remove [the snippet that prepends a `\` to greek letters](https://github.com/artisticat1/obsidian-latex-suite/blob/ff625642a0470264f20e556649a4ef278c663905/src/default_snippets.ts#L46).
- Change your snippet so that it is triggered by `\xii`, instead of `xii`.
  - You may need to give your snippet a higher priority, so that it takes precedence over [this snippet that inserts a space between greek letters and latin letters](https://github.com/artisticat1/obsidian-latex-suite/blob/ff625642a0470264f20e556649a4ef278c663905/src/default_snippets.ts#L50).

**Comment by XintakXVI** [comment]
Oh I didn't realise there was a snippet that prepends the `\`. Can't believe I missed that. 🙈

Thanks for your help 😌

**Comment by ndharari** [comment]
Hi! old thread but.. I hate the letter xi. theres a way to remove it altogether? im sure im never gonna use it lol

**Comment by XintakXVI** [comment]
I think you can just delete that line in the snippet editor. It should be under the section with all the other Greek letters.
@artisticat1 can confirm?

**Comment by ndharari** [comment]
This wont work... I want the prepend on the letters, but not on xi, and the GREEK definition is located in the plugin files. Could change those, but that would be overwritten any time an update comes!

**Comment by sleepycat233** [comment]
> Hi! old thread but.. I hate the letter xi. theres a way to remove it altogether? im sure im never gonna use it lol

`{trigger: "xi", replacement: "xi", options: "mA", priority: 1},`
